apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmbasic.resourceName" . }} #we are using chart and release so we need to pass root scope
  labels:
  {{- include "helmbasics.labels" . | upper }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/stacksimplify/kubenginx:4.0.0
        ports:
        - containerPort: 80
